
#################################
ip access-list extended POS_VLAN
remark ACQUIRER_NEW
permit ip any host 10.7.x.x
permit ip any host 10.8.x.x
remark VASLB
permit ip any host 10.9.x.x
deny ip any any
##################
%

!
ip access-list extended VTY-ACCESS
permit tcp host 10.1.9.213 any eq 22
permit tcp host 10.96.5.2 any eq 22
permit tcp host 10.96.5.5 any eq 22
permit tcp host 10.1.9.40 any eq 22
permit tcp host 10.1.9.140 any eq 22
permit tcp host 10.225.4.80 any eq 22
permit tcp host 10.224.24.174 any eq 22
permit tcp host 10.224.25.91 any eq 22
permit tcp host 10.1.9.201 any eq 22
permit tcp host 10.1.9.223 any eq 22
permit tcp host 10.1.12.109 any eq 22
permit tcp host 10.1.12.110 any eq 22
permit tcp host 10.1.12.111 any eq 22
permit tcp host 10.1.12.112 any eq 22
permit tcp host 10.2.96.225 any eq 22
deny ip any any log

!
ip access-list standard SNMP-IN
 permit 10.96.133.18
 permit 10.2.96.131
 permit 10.96.5.2
 permit 10.96.5.5
 permit 10.1.9.0 0.0.0.255
 deny any log
!
ip access-list standard NTT-SNMP-IN
permit 10.2.96.225
permit 10.2.96.226
permit 10.2.96.227
deny any log
!