banner
!
!
!
banner exec %
##########################################################################
#                                                                        #
#            **** Pick 'n Pay Information Systems ****                   #
#         ******* Unauthorised access prohibited *******                 #
#  In terms of Company Information Security Management Practices,        #
#  this Computer System is for authorised users ONLY.                    #
#  Individuals using this system WITH, WITHOUT or in EXCESS              #
#  of their authority are subject to having ALL their activities on      #
#  this system monitored and recorded for examination by any             #
#  authorised person. Any material so recorded may be disclosed          #
#  as appropriate.                                                       #
#  The following could also result in disciplinary actions taken:        #
#  i.   Damaging, deleting, altering or inserting data WITHOUT authority #
#  ii.  Fraudulent use of data                                           #
#  iii. Unauthorised disclosure of data                                  #
#  ANYONE USING THIS SYSTEM CONSENTS TO THESE TERMS                      #
#                                                                        #
#                                                                        #
#            ||        ||                            /\                  #
#            ||        ||                           /__\                 #
#           ||||      ||||                         /\  /\                #
#       ..:||||||:..:||||||:..                    /__\/__\               #
#                                                                        #
#      C I S C O  S Y S T E M S                  DIMENSION               #
#                                                ---- DATA               #
#                                                                        #
#                                                                        #
#                                                                        #
##########################################################################
%
!
!
banner login %
##########################################################################
#                                                                        #
#            **** Pick 'n Pay Information Systems ****                   #
#         ******* Unauthorised access prohibited *******                 #
#  In terms of Company Information Security Management Practices,        #
#  this Computer System is for authorised users ONLY.                    #
#  Individuals using this system WITH, WITHOUT or in EXCESS              #
#  of their authority are subject to having ALL their activities on      #
#  this system monitored and recorded for examination by any             #
#  authorised person. Any material so recorded may be disclosed          #
#  as appropriate.                                                       #
#  The following could also result in disciplinary actions taken:        #
#  i.   Damaging, deleting, altering or inserting data WITHOUT authority #
#  ii.  Fraudulent use of data                                           #
#  iii. Unauthorised disclosure of data                                  #
#  ANYONE USING THIS SYSTEM CONSENTS TO THESE TERMS                      #
#                                                                        #
#                                                                        #
#            ||        ||                            /\                  #
#            ||        ||                           /__\                 #
#           ||||      ||||                         /\  /\                #
#       ..:||||||:..:||||||:..                    /__\/__\               #
#                                                                        #
#      C I S C O  S Y S T E M S                  DIMENSION               #
#                                                ---- DATA               #
#                                                                        #
#                                                                        #
#                                                                        #
##########################################################################
%
!
!
banner motd %
##########################################################################
#                                                                        #
#            **** Pick 'n Pay Information Systems ****                   #
#         ******* Unauthorised access prohibited *******                 #
#  In terms of Company Information Security Management Practices,        #
#  this Computer System is for authorised users ONLY.                    #
#  Individuals using this system WITH, WITHOUT or in EXCESS              #
#  of their authority are subject to having ALL their activities on      #
#  this system monitored and recorded for examination by any             #
#  authorised person. Any material so recorded may be disclosed          #
#  as appropriate.                                                       #
#  The following could also result in disciplinary actions taken:        #
#  i.   Damaging, deleting, altering or inserting data WITHOUT authority #
#  ii.  Fraudulent use of data                                           #
#  iii. Unauthorised disclosure of data                                  #
#  ANYONE USING THIS SYSTEM CONSENTS TO THESE TERMS                      #
#                                                                        #
#                                                                        #
#            ||        ||                            /\                  #
#            ||        ||                           /__\                 #
#           ||||      ||||                         /\  /\                #
#       ..:||||||:..:||||||:..                    /__\/__\               #
#                                                                        #
#      C I S C O  S Y S T E M S                  DIMENSION               #
#                                                ---- DATA               #
#                                                                        #
#                                                                        #
#                                                                        #
##########################################################################
%
!
!