device-sensor accounting

device-sensor notify all-changes

mac address-table notification change

mac address-table notification mac-move
###############################################
%

!
mac address-table notification change
mac address-table notification mac-move
device-sensor accounting
device-sensor notify all-changes
!