snmp-server enable traps

snmp-server community SNMP_ACC1 SNMP-IN

snmp-server community SNMP_ACC1 RW SNMP-IN

snmp-server trap-source Vlan11

snmp-server view nms-view 1.3.6.1.2.1 included

snmp-server view nms-view 1.3.6.1.4.1.9 included

snmp-server group nms-group v3 priv read nms-view

snmp-server user snmpv3_user nms-group v3 auth sha xxxxx priv aes 128 xxxxx access SNMP-IN

snmp-server host 10.x.x.x traps version 3 priv snmpv3_user